### ISSUE TITLE
Aplicativo

### ISSUE THREAD

**Issue by labecfar2** [LaBECFar/sinae#1]
Na tela de configuração do app criar 8 campos de texto que serão usados pelo usuário para definir os tempos padrões de início e fim de cada quadrante.

Na hora que for processar um vídeo já carregar os valores desses campos automaticamente

**Comment by labecfar2** [comment]
Colocar um botão na tela de escolha dos tempos dos quadrantes para carregar os tempos padrões

**Comment by lkalsovik** [comment]
**Alterações feitas**

|Configuração|Nova análise|
|---|---|
|https://github.com/LaBECFar/sinae/commit/9a8aaff027e4571a7cbed32c749d6e19d62fceb7|https://github.com/LaBECFar/sinae/commit/b754b218b1d136ae2c2c3b4371de1dcb2c4627e9|
|![configuracoes](https://user-images.githubusercontent.com/4552123/74158982-be4eda00-4bf9-11ea-9533-5961a0d126c1.png)|![nova-analise](https://user-images.githubusercontent.com/4552123/74158989-c149ca80-4bf9-11ea-96a9-1b8d25eecfd9.png)|
