### ISSUE TITLE
Configuração

### ISSUE THREAD

**Issue by anselmobattisti** [LaBECFar/sinae#50]
Na tela de configuração, além dos campos de upload de arquivos, colocar o nome dos arquivos que já foram enviados previamente.

Isso será útil quando ele estiver testando para ver se os modelos que estão no servidor são os mais atualizados ou não

**Comment by lkalsovik** [comment]
Ao enviar um novo arquivo de configuração, o antigo é sobrescrito.

Isso se deve a necessidade do arquivo ter sempre o mesmo nome, para ser identificado dentro do algoritmo feito em Python que é usado no processamento dos frames e poços para identificar parasitas e motilidade.

Então existe somente um arquivo para cada configuração, e sempre será o ultimo enviado.
