### ISSUE TITLE
exportar CSV

### ISSUE THREAD

**Issue by labecfar2** [LaBECFar/sinae#6]
na primeira linha a coluna prev_ant deixar como vazio, hoje está repetindo o valor

**Comment by lkalsovik** [comment]
Agora todos os poços que são dos primeiros frames de cada quadrante tem o campo Previous_number do CSV vazio.

Feito em https://github.com/LaBECFar/sinae/commit/13aaa5fc68ee73f6e6c9c9a5bb1abead82108c1b
